"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['run.py']
DATA_FILES = []
#OPTIONS = {'iconfile':'images/logo192.png'}

setup(
    app=APP,
    data_files=DATA_FILES,
    setup_requires=['py2app'],
)

#options={'py2app': OPTIONS},
